version: "3.0"
services:
  webapp:
    environment:
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    image: dotlabs/apache:php${DOCKER_PHP_VERSION}
    volumes:
      - ".:/var/www/html/public"
    ports:
      - ${DOCKER_WEBAPP_PORT}:80
